
title: Devi Operations
email: contact@devioperates.com
description: >- 
  Devi Operates – IT Infra Support, DevOps, Platform Engineering, Webcam Services
baseurl: ""
url: "https://chennakesavabollepalli.github.io"
theme: minima
markdown: kramdown
